# Default values for prometheus-ethereum-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 31z4/ethereum-prometheus-exporter
  tag: v1.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9368

targetUrl: http://ethereum:8545

serviceMonitor:
  interval: 15s
  scrapeTimeout: 10s
