apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-ethereum-exporter.fullname" . }}
  labels:
{{ include "prometheus-ethereum-exporter.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prometheus-ethereum-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "prometheus-ethereum-exporter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -url
            - {{ .Values.targetUrl }}
          ports:
            - name: exporter
              containerPort: 9368
              protocol: TCP
