apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-ethereum-exporter.fullname" . }}
  labels:
{{ include "prometheus-ethereum-exporter.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: exporter
      port: {{ .Values.service.port }}
      targetPort: 9368
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "prometheus-ethereum-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
